Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,6 +12,22 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+      - name: Run Local Test
+        run: |
+          # Run Docker Compose locally
+          docker-compose up -d
+
+          # Wait for a moment to let containers start
+          sleep 20
+
+          # Test if the app is running by making a request to 172.28.1.3:5000
+          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://172.28.1.3:5000)
+
+          # Exit if response code is not 200
+          if [ $response_code -ne 200 ]; then
+            echo "Local test failed with response code: $response_code"
+            exit 1
+          fi
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
